version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: health_first_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: healthfirst_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changed external port to avoid conflicts
    networks:
      - healthfirst_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"  # Changed external port to avoid conflicts
    volumes:
      - redis_data:/data
    networks:
      - healthfirst_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:healthfirst_password_2024@db:5432/health_first_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-django-key-change-this-in-production-docker
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - healthfirst_network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        echo 'Starting server...' &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 --reload healthfirst.wsgi:application
      "

  # Celery Worker
  celery:
    build: .
    restart: unless-stopped
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:healthfirst_password_2024@db:5432/health_first_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-django-key-change-this-in-production-docker
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    volumes:
      - ./media:/app/media
    depends_on:
      - db
      - redis
    networks:
      - healthfirst_network
    command: celery -A healthfirst worker --loglevel=info

  # Celery Beat (for scheduled tasks)
  celery-beat:
    build: .
    restart: unless-stopped
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:healthfirst_password_2024@db:5432/health_first_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-django-key-change-this-in-production-docker
    depends_on:
      - db
      - redis
    networks:
      - healthfirst_network
    command: celery -A healthfirst beat --loglevel=info

volumes:
  postgres_data:
  redis_data:

networks:
  healthfirst_network:
    driver: bridge 